Use cabal in travis builds.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -6,11 +6,8 @@ dist: trusty
 #   - riak
 
 before_install:
-  # stack
-  - mkdir -p ~/.local/bin
-  - export PATH=~/.local/bin:$PATH
-  - curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.6.0/stack-0.1.6.0-linux-x86_64.tar.gz | tar xz -C /tmp; mv /tmp/stack-0.1.6.0-linux-x86_64/stack ~/.local/bin
-  - ulimit -n 4096
+  # Cabal
+  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
   # riak
   - sudo apt-get -y install build-essential libc6-dev-i386 git
   - sudo apt-get -y install erlang-nox erlang-dev erlang-reltool
@@ -43,23 +40,38 @@ before_install:
 
 matrix:
   include:
-    - env: GHCVER=7.8.4 STACK_YAML=stack.yaml RIAK=2.1.3
+    - env: GHCVER=7.8.4 RIAK=2.1.3
       addons: {apt: {packages: [ghc-7.8.4], sources: [hvr-ghc]}}
-    - env: GHCVER=7.8.4 STACK_YAML=stack.yaml RIAK=2.0.6
+    - env: GHCVER=7.8.4 RIAK=2.0.6
       addons: {apt: {packages: [ghc-7.8.4], sources: [hvr-ghc]}}
-    - env: GHCVER=7.10.3 STACK_YAML=stack-7.10.yaml RIAK=2.1.3
-      addons: {apt: {packages: [ghc-7.10.3],sources: [hvr-ghc]}}
-    - env: GHCVER=7.10.3 STACK_YAML=stack-7.10.yaml RIAK=2.0.6
-      addons: {apt: {packages: [ghc-7.10.3],sources: [hvr-ghc]}}
-    - env: GHCVER=head STACK_YAML=stack-head.yaml RIAK=2.1.3
-      addons: {apt: {packages: [cabal-install-head,ghc-head],  sources: [hvr-ghc]}}
-
-  allow_failures:
-   - env: GHCVER=head STACK_YAML=stack-head
+    - env: GHCVER=7.10.3 RIAK=2.1.3
+      addons: {apt: {packages: [ghc-7.10.3], sources: [hvr-ghc]}}
+    - env: GHCVER=7.10.3 RIAK=2.0.6
+      addons: {apt: {packages: [ghc-7.10.3], sources: [hvr-ghc]}}
+    - env: GHCVER=8.0.1 RIAK=2.1.3
+      addons: {apt: {packages: [ghc-8.0.1], sources: [hvr-ghc]}}
 
 install:
-  - stack --no-terminal --skip-ghc-check setup
-  - stack --no-terminal --skip-ghc-check test --only-snapshot
+ - cabal --version
+ - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+ - travis_retry cabal update
+ - cabal install --only-dependencies --enable-tests --enable-benchmarks
 
+# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
 script:
-  - stack --no-terminal --skip-ghc-check test
+ - if [ -f configure.ac ]; then autoreconf -i; fi
+ - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
+ - cabal build   # this builds all libraries and executables (including tests/benchmarks)
+ - cabal test
+ - cabal check
+ - cabal sdist   # tests that a source-distribution can be generated
+
+# The following scriptlet checks that the resulting source distribution can be built & installed
+ - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
+   cd dist/;
+   if [ -f "$SRC_TGZ" ]; then
+      cabal install --force-reinstalls "$SRC_TGZ";
+   else
+      echo "expected '$SRC_TGZ' not found";
+      exit 1;
+   fi
